export const RESET_INITIAL_STATE = 'R;ESET_INITIAL_STATE'
export const CREATE_INITIAL_POSTS_PROGRESS = 'CREATE_INITIAL_POSTS_PROGRESS';
export const CREATE_INITIAL_POSTS_FAILURE = 'CREATE_INITIAL_POSTS_FAILURE';
export const CREATE_INITIAL_POSTS_SUCCESS = 'CREATE_INITIAL_POSTS_SUCCESS';

export const UPDATE_INITIAL_POSTS_PROGRESS = 'UPDATE_INITIAL_POSTS_PROGRESS';
export const UPDATE_INITIAL_POSTS_FAILURE = 'UPDATE_INITIAL_POSTS_FAILURE';
export const UPDATE_INITIAL_POSTS_SUCCESS = 'UPDATE_INITIAL_POSTS_SUCCESS';

export const FETCH_POSTS_PROGRESS = 'FETCH_POSTS_PROGRESS';
export const FETCH_POSTS_FAILURE = 'FETCH_POSTS_FAILURE';
export const FETCH_POSTS_SUCCESS = 'FETCH_POSTS_SUCCESS';